language: r

r:
  - oldrel
  - release
  - devel

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
