language: r

sudo: true

warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

#install:
#  - R -e "0" --args --bootstrap-packrat
#  - R -e "packrat::restore(restart = FALSE)"

#cache:
#  directories:
#    - $TRAVIS_BUILD_DIR/packrat/src
#    - $TRAVIS_BUILD_DIR/packrat/lib
#  packages: true

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_binary_packages:
  - covr
  - plotly
  - RColorBrewer
  - ggplot2
  - scales
  - httr
  - jsonlite
  - magrittr
  - digest
  - viridisLite
  - base64enc
  - htmltools
  - htmlwidgets
  - tidyr
  - hexbin
  - dplyr
  - tibble
  - lazyeval
  - rlang
  - crosstalk
  - purrr
  - data.table
  - promises
  - R6
  - shiny
  - assertthat
  - bindrcpp
  - glue
  - pkgconfig
  - Rcpp
  - tidyselect
  - gtable
  - MASS
  - mgcv
  - plyr
  - reshape2
  - withr
  - lattice
  - yaml
  - curl
  - mime
  - openssl
  - later
  - labeling
  - munsell
  - cli
  - crayon
  - fansi
  - pillar
  - stringi
  - bindr
  - nlme
  - Matrix
  - colorspace
  - askpass
  - utf8
  - stringr
  - httpuv
  - xtable
  - sourcetools
  - sys

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - shosaco_nospam@hotmail.com
    on_success: always # default: change
    on_failure: always # default: always
