language: r

sudo: true

warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

#install:
#  - R -e "0" --args --bootstrap-packrat
#  - R -e "packrat::restore(restart = FALSE)"

#cache:
#  directories:
#    - $TRAVIS_BUILD_DIR/packrat/src
#    - $TRAVIS_BUILD_DIR/packrat/lib
#  packages: true

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

# to speed up building:
# pkg <- unlist(tools::package_dependencies(c("devtools", "vistime"), db = available.packages(), which = c("Depends", "Imports"), recursive = TRUE))
# pkg2 <- pkg[!pkg %in% c("tools", "methods", "utils", "grid", "stats", "graphics", "grdevices")]
# pkg3 <- unique(c("devtools", "evaluate", "highr", "knitr", "markdown", "praise", "rmarkdown", "testthat", "tinytex", "xfun"), pkg2)
# cat("   -", paste(pkg2, collapse = "\n  - "))
r_binary_packages:
  - devtools
  - callr
  - cli
  - digest
  - git2r
  - httr
  - jsonlite
  - memoise
  - pkgbuild
  - pkgload
  - rcmdcheck
  - remotes
  - rstudioapi
  - sessioninfo
  - usethis
  - withr
  - processx
  - R6
  - assertthat
  - crayon
  - curl
  - mime
  - openssl
  - desc
  - prettyunits
  - rprojroot
  - rlang
  - xopen
  - clipr
  - clisymbols
  - fs
  - gh
  - glue
  - whisker
  - Rcpp
  - ini
  - askpass
  - magrittr
  - ps
  - backports
  - sys
  - plotly
  - RColorBrewer
  - ggplot2
  - scales
  - httr
  - jsonlite
  - magrittr
  - digest
  - viridisLite
  - base64enc
  - htmltools
  - htmlwidgets
  - tidyr
  - hexbin
  - dplyr
  - tibble
  - lazyeval
  - rlang
  - crosstalk
  - purrr
  - data.table
  - promises
  - R6
  - shiny
  - assertthat
  - bindrcpp
  - glue
  - pkgconfig
  - Rcpp
  - tidyselect
  - gtable
  - MASS
  - mgcv
  - plyr
  - reshape2
  - withr
  - lattice
  - grDevices
  - yaml
  - curl
  - mime
  - openssl
  - later
  - labeling
  - munsell
  - cli
  - crayon
  - fansi
  - pillar
  - stringi
  - bindr
  - nlme
  - Matrix
  - colorspace
  - askpass
  - utf8
  - stringr
  - httpuv
  - xtable
  - sourcetools
  - sys

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - shosaco_nospam@hotmail.com
    on_success: always # default: change
    on_failure: always # default: always
